config/routes.rb
Teste::Application.routes.draw do
  resources :desafios

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/desafio.rb
class Desafio < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/desafios_controller.rb
class DesafiosController < InheritedResources::Base
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/desafios_helper.rb
module DesafiosHelper
end

app/views/desafios/_form.html.erb
<%= form_for(@desafio) do |f| %>
  <% if @desafio.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@desafio.errors.count, "error") %> prohibited this desafio from being saved:</h2>

      <ul>
      <% @desafio.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br>
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :desafio %><br>
    <%= f.text_area :desafio %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/desafios/edit.html.erb
<h1>Editing desafio</h1>

<%= render 'form' %>

<%= link_to 'Show', @desafio %> |
<%= link_to 'Back', desafios_path %>

app/views/desafios/index.html.erb
<h1>Listing desafios</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Email</th>
      <th>Desafio</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @desafios.each do |desafio| %>
      <tr>
        <td><%= desafio.nome %></td>
        <td><%= desafio.email %></td>
        <td><%= desafio.desafio %></td>
        <td><%= link_to 'Show', desafio %></td>
        <td><%= link_to 'Edit', edit_desafio_path(desafio) %></td>
        <td><%= link_to 'Destroy', desafio, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Desafio', new_desafio_path %>

app/views/desafios/new.html.erb
<h1>New desafio</h1>

<%= render 'form' %>

<%= link_to 'Back', desafios_path %>

app/views/desafios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @desafio.nome %>
</p>

<p>
  <strong>Email:</strong>
  <%= @desafio.email %>
</p>

<p>
  <strong>Desafio:</strong>
  <%= @desafio.desafio %>
</p>

<%= link_to 'Edit', edit_desafio_path(@desafio) %> |
<%= link_to 'Back', desafios_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Teste</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>